# Generated by Django 3.2.4 on 2021-06-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habergir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberler',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Kullanıcı'),
            preserve_default=False,
        ),
    ]
